# Generated by Django 3.2.7 on 2021-09-09 08:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField()),
                ('main_image', models.ImageField(default='images/pexels-arnie-watkins-3156482.jpg', upload_to='images/')),
                ('title', models.CharField(max_length=300)),
                ('desc', models.TextField(default='QUAP')),
                ('focus_content', models.TextField(default='QUAP')),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('author', models.CharField(default='Team QUAP', max_length=50)),
                ('tags', models.CharField(default='used auto parts', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('part', models.CharField(max_length=200, null=True)),
                ('brand', models.CharField(max_length=200, null=True)),
                ('customer_name', models.CharField(max_length=200, null=True)),
                ('customer_phone', models.CharField(max_length=200, null=True)),
                ('customer_email', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailSubscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, null=True)),
                ('product_image', models.ImageField(default='products/default.jpg', upload_to='products/')),
            ],
        ),
        migrations.CreateModel(
            name='StateCityList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIPSCode', models.IntegerField()),
                ('state', models.CharField(max_length=100)),
                ('stateAbbreviation', models.CharField(max_length=10)),
                ('countyCode', models.CharField(max_length=10)),
                ('countyName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Years',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_name', models.IntegerField()),
            ],
        ),
    ]
