# Generated by Django 3.2.7 on 2021-09-09 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_products_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_image',
            field=models.ImageField(default='products/default.jpg', upload_to='products/'),
        ),
    ]
